import type { Metadata } from "next";
import "./globals.css";

import { Roboto } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

