import type { Metadata } from "next";
import "./globals.css";

import { Roboto } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} flex h-screen flex-col items-center justify-between w-full`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

